spring:
  application:
    name: reviewservice
  datasource:
    url: jdbc:postgresql://localhost:5432/store-db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  instance:
    hostname: localhost
