spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:postgresql://localhost:5432/store-db
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  instance:
    hostname: localhost

info:
  app:
    name: "Order Service"
    version: "1.0.0"
    description: "This microservice allows users to add products to the shopping cart, manage the cart, and place orders."
    author: "Svetlana Martynova"


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
          status:
            http-mapping:
              up: 207
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true
