server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: productservice
          uri: http://localhost:8081/
          predicates:
            - Path=/api/products/**
        - id: orderservice
          uri: http://localhost:8082/
          predicates:
            - Path=/api/shoppingCart/**
        - id: reviewservice
          uri: http://localhost:8083/
          predicates:
            - Path=/reviews/**



